export const ETAPPECLASSIFICATION = 'ETAPPECLASSIFICATION';
export const TOURCLASSIFICATION = 'TOURCLASSIFICATION';
export const YOUTHCLASSIFICATION = 'YOUTHCLASSIFICATION';
export const MOUNTAINCLASSIFICATION = 'MOUNTAINCLASSIFICATION';
export const POINTSCLASSIFICATION = 'POINTSCLASSIFICATION';
