language: node_js
node_js:
- "10.0.0"
branches:
  only:
  - development
before_script:
- npm install -g @angular/cli
script:
- echo "Deploy!!"
- ng build --prod
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project wielerspel-aec4b --token $FIREBASE_TOKEN
