language: node_js
node_js:
- "10.10.0"
branches:
  only:
  - development
before_script:
- npm install -g @angular/cli
script:
- echo "Deploy!!"
- npm install
- ng build --prod
install:
- npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "wielerspel-aec4b"
